language: haskell
ghc: 7.8
branches:
  only:
  - master
before_install:
  - rm .cabal-sandbox.tar.gz
  #- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  #- travis_retry sudo apt-get update
  #- travis_retry sudo apt-get install --force-yes cabal-install-1.22
  #- export PATH=~/.cabal/bin:$PATH
install:
  - cabal sandbox init
  - cabal install -j --disable-documentation -fhttps hakyll
  - cabal install -j --disable-documentation --disable-tests --reorder-goals
before_deploy:
  - tar czf cabal-sandbox.tar.gz .cabal-sandbox
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  file: cabal-sandbox.tar.gz
  on:
    tags: true
