env:
  - CABALVER=1.22 GHCVER=7.8.4 STACKAGEVER=${TRAVIS_TAG:-lts-1}

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal

branches:
  only:
  - master

# Note: the distinction between `before_install` and `install` is not important.
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal sandbox init

  - export CABAL_CONF_URL=http://www.stackage.org/snapshot/$STACKAGEVER/cabal.config
  - echo Download cabal.config from stackage: $CABAL_CONF_URL
  - curl $CABAL_CONF_URL -O ~/.cabal/cabal.config
  - travis_retry cabal update
  - cabal install -j --disable-documentation -fhttps hakyll
  - cabal install -j --disable-documentation --disable-tests --reorder-goals

before_deploy:
  - rm -f .cabal-sandbox.tar.gz
  - tar czf cabal-sandbox.tar.gz .cabal-sandbox

deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  file: cabal-sandbox.tar.gz
  on:
    tags: true
